### ISSUE TITLE
Python interface

### ISSUE THREAD

**Issue by Aleksej9521** [asarmadi/unitree_b1#1]
Hi, great repo :) I wanna use it to test on real B1 robot. But I have problems with the python interface. I always have the error:

"ImportError: libunitree_legged_sdk.so: cannot open shared object file: No such file or directory"

How do you solve it ?

**Comment by asarmadi** [comment]
Hi, after building Unitree B1 SDK (you can find the instructions here: [Unitree SDK](https://github.com/unitreerobotics/unitree_legged_sdk)), you need to edit "rb_interface.py" file line 4. You need to change the path to the corresponding path on your system.

**Comment by Aleksej9521** [comment]
Hi, at the end I solved. But to have it works on my pc, I needed to recompile the .so file.
