### ISSUE TITLE
Different parameters urdf b1 

### ISSUE THREAD

**Issue by Aleksej9521** [asarmadi/unitree_b1#2]
Hi, I was checking the urdf of b1 in this repository and I saw that it is different from the one in official repository of unitree: https://github.com/unitreerobotics/unitree_ros/blob/master/robots/b1_description/xacro/b1.urdf. Why ? Are your urdf compatible with the real robot?

**Comment by asarmadi** [comment]
Hi, thanks for pointing out! that's correct. When the code was written, the official urdf was not out. It is recommended to use the official urdf file.
